---
# Test setup.
scanPath: /path_to_scans/
outputFileName: /path_to_output_files/fileName
kitti: false

# Algorithm configuration.
sigma: 0.35
rMap: 2
rNew: 0.5
convergenceTol: 1e-3
minSensorRange: 10

# Hardware configuration.
maxSensorRange: 120