---
# Test setup.
scanPath: /path_to_scans/velodyne/
outputFileName: /path_to_output_files/fileName
kitti: true

# Algorithm configuration.
sigma: 0.3
rMap: 2.0
rNew: 0.5
convergenceTol: 1e-3
minSensorRange: 10

# Hardware configuration.
maxSensorRange: 80