---
# Test setup.
scanPath: /path_to_scans/velodyne/
outputFileName: /path_to_output_files/fileName
kitti: false

# Algorithm configuration.
sigma: 0.5
voxelSizeMap: 1.0
voxelSizeScan: 1.0
convergenceTol: 1e-6
minSensorRange: 1

# Hardware configuration.
maxSensorRange: 100