#ifndef OBJECTIVE_FUNCTION_H
#define OBJECTIVE_FUNCTION_H

#include "helper.h"

/**
 * @brief The objective function used by the optimisation solver to find the
 *        best homogeneous transform that aligns the new scan with the submap.
 *        The only configuration parameter used here is sigma to score each
 *        point in the new scan.
 */
class ObjectiveFunction
{
    private:
        double sigma_;   // registration parameter
        Eigen::MatrixXd scan_;          // target scan
        int scanSize_;                  // length of the output scan
        my_kd_tree_t *subMapKdTree_;    // submap Kd tree

    public:

        /**
         * @brief Constructor to initialise member variables.
         * 
         * @param uncertainty       Generated by the user configuration parameter, sigma. 
         * @param scan              The scan to register to subMap.
         * @param sourceScanKdTree  A KdTree of the subMap.
         */

        ObjectiveFunction(double sigma, Eigen::MatrixXd scan,
                          my_kd_tree_t *sourceScanKdTree);

        // overload function call operator


        /**
         * @brief Overload the function call operator.
         * 
         * @param m         Homogeneous vector hypothesis to register the scan to the subMap.
         * @return double   The registration score (sum of the score for each point).
         */
        double operator()(const column_vector& m) const;
};

#endif